### ISSUE TITLE
No G-Code Viewer only on Pi Screen

### ISSUE THREAD

**Issue by cosmith71** [BillyBlaze/OctoPrint-TouchUI#101]
First of all, thanks for the work.  It is greatly appreciated.

I'm having a strange issue with TouchUI.  I'm running it on a RPi 3 with the official 7" touchscreen.  On this touchscreen, the G-Code Viewer does not appear in the menu.  Everything else seems to be working OK.  If I log on with any other device, it's there.  Any suggestions?

Thanks,

--Colin

**Comment by BillyBlaze** [comment]
Your welcome 👍 The G-code Viewer is disabled on Touchscreen devices for performance. You could go TouchUI Settings and disable Touchscreen mode, however it is highly recommended not do this because the Gcode-viewer might/will crash your Chromium and interfere with the print job. Depending on the size of the Gcode.

**Comment by cosmith71** [comment]
Ah.  I'm happy to report it is working perfectly then!  No big deal, I just noticed it was missing and had been there before, so I was wondering what I broke.  ;)

**Comment by BillyBlaze** [comment]
Awesome :) Also thanks for reporting, please feel free to add any issue if needed.
