### ISSUE TITLE
Feature request: Showing IP on the screen

### ISSUE THREAD

**Issue by trgtylcnky** [BillyBlaze/OctoPrint-TouchUI#108]
Hi,
I think it would be cool if we can see the ip address (maybe taken by `hostname -I`) at somewhere on the screen. I know it is easy to find the ip by searching network but it would be good.

Thanks,

**Comment by BillyBlaze** [comment]
Hi,

Thanks for submitting the feature request. 

I will not implement any additional functionality to this plugin beside anything related to it's core functionality. e.g. providing a mobile and touchscreen friendly interface. 

However, since TouchUI only transforms the layout you can still install additional plugins on OctoPrint to show the IP address.

Please feel free to submit a feature request to support a specific plugin.
