### ISSUE TITLE
A more poor-touchscreen-friendly UI

### ISSUE THREAD

**Issue by trgtylcnky** [BillyBlaze/OctoPrint-TouchUI#124]
Hi, 
I am using TouchUI for a while. Sometimes I am struggling with my touch-screen, especially when clicking dropdown menu items. I don't know why but I see mouse pointer jumps to the up-left corner of the screen so dropdown menu is closed because I clicked somewhere else.
So, I have an idea. Dropdown menu can be designed like another tab. Then it doesn't lose focus unless we specifically click another tab.
Thanks,

**Comment by BillyBlaze** [comment]
Hi, Thanks for reporting. The jumping of the cursor sounds like it's caused by the driver with an incorrect calibration. Atleast that is the behavior I noticed on my own 3.5" touchscreen. I would encourage - rather then fighting it - to fix the source of this issue. 

I am open for screen-estate improvements (which 1.0.0 will do) but I won't fight a battle with issues caused by specific drivers.
