### ISSUE TITLE
Change the text on bootup

### ISSUE THREAD

**Issue by Mte90** [BillyBlaze/OctoPrint-TouchUI#130]
Actually when the TouchUi start the logo is TouchUI text, it is possible to change in the settings with someone else?

**Comment by BillyBlaze** [comment]
There is no way to change this within the settings. The TouchUI logo are inline SVG, the only way you can change this is by manual editing [the html](https://github.com/BillyBlaze/OctoPrint-TouchUI-autostart/blob/master/load-screen/startup.html) within the bootloader found under `~/TouchUI-autostart/load-screen/startup.html`

**Comment by Mte90** [comment]
A file upload for a SVG can be an idea for it :-)

**Comment by BillyBlaze** [comment]
That is sadly not possible, the bootloader are static files that are loaded directly from the file system, There is no server, database or OctoPrint involved, which makes customization hard and therefor it's better for those few cases to manually change the file themself.

Never the less thanks for your feedback!

**Comment by Mte90** [comment]
We are talking about the touchui logo, it is not possible to do a symlink to a different file?

**Comment by BillyBlaze** [comment]
Yes, but you would still be required to edit the static HTML and refer to the new file location. Which will also cause the git update mechanism to not work. We could ofcourse move this to a config file, but then you would still be required to edit that config file. 

*edit*
sorry, you also mentioned a symlink; again this is possible but would still break the update mechanism, since the contents has been changed.

**Comment by Mte90** [comment]
The important that is possible to change that logo, a config file is not a problem for me :-)
