### ISSUE TITLE
Wrong 'main color' picked up when running multiple OctoPrint instances on he same server. 

### ISSUE THREAD

**Issue by joris57** [BillyBlaze/OctoPrint-TouchUI#132]
I am running multiple instances of OctoPrint on different ports of the same (Ubuntu) server. To differentiate between them, I set a different 'appearance' color in OctoPrint.

In TouchUI, I set a matching 'main color'.

However, this color is not correctly displayed in Chrome (usually the same color from one of the three instances is displayed for all 3 instances). The 'regular' interface picks up the 'appearance' color correctly.

**Comment by BillyBlaze** [comment]
Thanks for reporting, sorry but this is simply not possible since the code was not made with the intention of having multiple instances on one OctoPrint.

To support this; It would require a major refactoring of the code on the backend-end (Python) and the mechanism on the front-end (Javascript) that compiles the LESS files into a CSS file.

However, since I don't have much time on my hands at the moment, I can't implement this soon. I also needs some "standard documentation" about setting up multiple instances so I can rely on a consistent mechanisme for storing the and serving the right compiled CSS file.

**Comment by joris57** [comment]
Thanks for considering this.

Instructions for setting up multiple instances can be found here : [https://github.com/foosel/OctoPrint/issues/113](url). This is the only 'standard' I have found.

Note that TouchUI seems in general to work well for multiple instances, with exception of this color issue.

**Comment by gdachs** [comment]
You could use a docker container with octoprint inside. You can start multiple containers with just different ports. They will have their own file systems, so different colors would be no problem.

**Comment by BillyBlaze** [comment]
Thanks for posting @gdachs, this is a very good alternative, therefor I am closing this issue.

Once OctoPrint officially support multiple instances I am willing to reconsider any changes needed with customization.

**Comment by joris57** [comment]
I understand that the developer does not want to put in significant effort for the implementation of what certainly is merely a cosmetic issue, but calling having to learn about 'docker' a 'very good alternative' is cutting it a bit short.

**Comment by BillyBlaze** [comment]
yeah, your right. After reconsidering it, I think I could easily fix this by appending OctoPrint's port number to the filename. You do run the same instance on two different ports right?

**Comment by joris57** [comment]
I'm not sure if I interpret 'instance' in your question correctly, but I guess the answer is 'yes'.

I'm starting the 'octoprint' daemon multiple (3 at the moment) times with a different basedir, config file and port.

**Comment by BillyBlaze** [comment]
Yeah, I meant OctoPrint instances. I could write the customization for each instance to a file like `touchui.custom.5000.css` instead of `touchui.custom.css`. That wouldn't require a lot of refactoring too. Most of the pain is going to be in migrating old settings and files into new ones that also include the port.

Anyhow; I'll add this in the next release.

**Comment by BillyBlaze** [comment]
Sorry, was adding a new bot to github, you can ignore what he said ofcourse.

**Comment by BillyBlaze** [comment]
Thanks, this has been released in 0.3.12
