### ISSUE TITLE
Issue with 7 inch touchscreen

### ISSUE THREAD

**Issue by Penged** [BillyBlaze/OctoPrint-TouchUI#160]
I installed  Octoprint by using the fresh Octoprint-Image on an SD-Card. I had installed a 7 Inch Raspberry TFT.
Then i had installed TouchUI like the Manual Boot to Browser Jessie Light. Everthing works .
If i reboot the System runs up, then the TFT shows TouchUI connecting and after a while the Text became red and i see a Message "Connecting to TouchUI failed".
   This issue was on a different thread that was resolved by finalizing the installation of octoprint. I was asked to share my octoprint.log before I was asked to create a new post. I am not sure how to finalize the installation or how to find my octoprint.log. Sorry I am not more skilled in this. Any help would be greatly appreciated.

**Comment by BillyBlaze** [comment]
Hi @Penged,

Have you installed TouchUI within the OctoPrint plugin manager?

If not;
1. Open octoprint webinterface
1. Goto the Settings
1. Goto the Plugin Manager
1. Click on "Install more" on the bottom
1. Search for TouchUI and install it 👍

**Comment by Penged** [comment]
Sorry for the delay in responding. Yes, I have TouchUI installed. I can access octoprint from my laptop but not on the 7 inch TFT screen
How do I find and print my octopi.log?

**Comment by Penged** [comment]
Well I have made progress. I have managed to get it to start up on the TFT screen but it does not seem to connect to my printer. I have a Rostock max V2 with a stock rambo board.

**Comment by ticals1000** [comment]
you have to sign in on the touchscreen, open the menu on the top right then enable virtual keyboard, then click on sign in and use your octopi account to sign in

**Comment by Penged** [comment]
Yes, I have got it working. One last question. Can I run the touchscreen without having octoprint started on my laptop?

**Comment by ticals1000** [comment]
Of course


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Penged <notifications@github.com> Date: 10/20/17  7:27 AM  (GMT-05:00) To: BillyBlaze/OctoPrint-TouchUI <OctoPrint-TouchUI@noreply.github.com> Cc: ticals1000 <lilcal33@yahoo.com>, Comment <comment@noreply.github.com> Subject: Re: [BillyBlaze/OctoPrint-TouchUI] Issue with 7 inch touchscreen (#160) 
Yes, I have got it working. One last question. Can I run the touchscreen without having octoprint started on my laptop?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BillyBlaze/OctoPrint-TouchUI","title":"BillyBlaze/OctoPrint-TouchUI","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BillyBlaze/OctoPrint-TouchUI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Penged in #160: Yes, I have got it working. One last question. Can I run the touchscreen without having octoprint started on my laptop?"}],"action":{"name":"View Issue","url":"https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/160#issuecomment-338180428"}}}

**Comment by terracedr** [comment]
Penged "Well I have made progress. I have managed to get it  to start up on the TFT screen but it does not seem to connect to my  printer. I have a Rostock max V2 with a stock rambo board."
----------------------------------------------------------------------------------------------------
Wondering how you fixed the problem of Octopint loaded with out TouchUI? I now am having the same issue after a new image disk with Octoprint and TouchUi is installed in the plugins of the web inter face of Octoprint. However, I cannot get the RP 7" inch screen to load the TouchUI. PLEASE HELP>

**Comment by Penged** [comment]
terracedr, 
    I dont rememeber how I got it to work. I tried startting my printer and then the touchscreen, or vice versa. I did connect after a few tries. I In the end I scrapped the project. It was more effective to start prints off my laptop through octoprint

**Comment by ticals1000** [comment]
You have to follow the directions for the "boot to browser" using raspbian jessie light after you have "already installed" touchui.   https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light) The only thing that is not in the directions though is that you have to create the xwrapper.config first in /etc/X11/Xwrapper.config.  otherwise it looks like everything goes through fine but it does not


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: terracedr <notifications@github.com> Date: 11/5/17  7:21 PM  (GMT-05:00) To: BillyBlaze/OctoPrint-TouchUI <OctoPrint-TouchUI@noreply.github.com> Cc: ticals1000 <lilcal33@yahoo.com>, Comment <comment@noreply.github.com> Subject: Re: [BillyBlaze/OctoPrint-TouchUI] Issue with 7 inch touchscreen (#160) 
Penged "Well I have made progress. I have managed to get it  to start up on the TFT screen but it does not seem to connect to my  printer. I have a Rostock max V2 with a stock rambo board."
Wondering how you fixed the problem of Octopint loaded with out TouchUI? I now am having the same issue after a new image disk with Octoprint and TouchUi is installed in the plugins of the web inter face of Octoprint. However, I cannot get the RPU 7" inch screen to load the TouchUI. PLEASE HELP>

**Comment by BillyBlaze** [comment]
Closing this issue since the OP resolved it and is not using it anymore.

For sake of my sanity, please create a new issue if you're having issues.
