### ISSUE TITLE
[REQUEST] Either collapse FILES list or UPLOAD button on "top"?

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#210]
Whenever you have a long list of printable files listed, i have to each time scroll down the list all the way down to find the UPLOAD button, which is quite tedious and sometimes slow too.

Can't the Files list be collapsed OR add (another?) UPLOAD button on TOP of the Files section??

Thanks!

**Comment by bolsoncerrado** [comment]
This means NO thanks?

**Comment by BillyBlaze** [comment]
No, it means I have no time on my hands to look into this due to real life situation. I have added a pending label so that the bot will ignore this.

**Comment by bolsoncerrado** [comment]
Sorry to hear that. Hope all improves.

**Comment by BillyBlaze** [comment]
Thanks for reporting this feature request.

I will release in the upcoming version an extra button on top of the files list so that you can easily access the upload functionality without scrolling.

It will look like this:
![image](https://user-images.githubusercontent.com/445608/44960973-4f9c2600-af09-11e8-8f03-1ac8db575250.png)

**Comment by bolsoncerrado** [comment]
Thank YOU
