### ISSUE TITLE
Does TouchUI support GCode viewer plugin? also I have many "?" instead of icons showing

### ISSUE THREAD

**Issue by crafttherapy** [BillyBlaze/OctoPrint-TouchUI#243]
I need a bit of help getting my TouchUI environment looking right. 

I tried to use icons in the settings but they just overlapped the white default settings. 

also, I noticed i don't have GCode viewer on my touch panel, but from a web browser on a pc I have it. Does TouchUI support it?

Thanks for a great product!!!

**Comment by BillyBlaze** [comment]
Hi,

The GCode viewer is disabled in touchscreen mode due to the heavy load (CPU/Memory) it generates. We don't want those loads to intervene with the performance of your 3d printer.

The question mark icons are plugins that are not - yet - supported, but that doesn't mean users can install and use those plugins in touchui.

Your welcome! 👍
