### ISSUE TITLE
Network connecting from TouchUi to local PC

### ISSUE THREAD

**Issue by JBSullivan** [BillyBlaze/OctoPrint-TouchUI#250]
I`m using TouchUI with a 7" Display. Is there any way to upload a new file, catching it from my local PC to upload it via TouchUI to the Octoprint folders?

In the "Open Files" Window of TouchUI i did not found any Network option
to navigate to my local PC and select the wanted file.

**Comment by BillyBlaze** [comment]
I haven't tried any of this for myself, but this should be technically possible by installing and configuring samba.

For example some guides:
- https://www.opentechguides.com/how-to/article/raspberry-pi/86/shared-folder-windows.html
- https://raspberrypihq.com/how-to-share-a-folder-with-a-windows-computer-from-a-raspberry-pi/

I can't give you support on this since I have no experience with this, good luck!
