### ISSUE TITLE
TouchUI Doesn't Load Properly if using Reverse Proxy

### ISSUE THREAD

**Issue by Enverex** [BillyBlaze/OctoPrint-TouchUI#294]
I have Octoprint configured to use a sub-folder for the purposes of a reverse proxy to other machines. TouchUI obviously doesn't need to use this, but it seems having one set breaks most the content from loading. Instead of the normal page, you get a black page with blue text, which appears to be the entire of Octoprint, but without any CSS or Javascript loaded. Removing the reverse proxy line from Octoprint "fixes" this, but obviously breaks it for everything else as it'll no-longer work behind the proxy.

For reference, the lines in Octoprint used to do this are:

```
  reverseProxy:
    prefixFallback: /subfoldergoeshere
```

I can't see any way of handling this in TouchUI if it needs special configuration.

**Comment by BillyBlaze** [comment]
Hi @Enverex,

Thanks for reporting. I think this issue is more related to OctoPrint then to TouchUI, all the files served by TouchUI are bundled by OctoPrint and served by OctoPrint. We do have an API call to generate the customization, but that URL is served relatively and should work with subfolders.
