### ISSUE TITLE
touch UI setting not open, and mobile not detect

### ISSUE THREAD

**Issue by devildant** [BillyBlaze/OctoPrint-TouchUI#299]
Hello,
I am under OctoPrint 1.3.11rc3, I can not open touch settings, and mobile detection does not work.
I do not have an error in the console

**Comment by jneilliii** [comment]
I can confirm this same thing in 1.3.11rc3 in Chrome. Attempting a force of touchUI using `#touch` at the end of the url doesn't force touchui to load either.

**Comment by BillyBlaze** [comment]
Thanks for reporting! I can reproduce this issue and I'll fix it in the upcoming release.

**Comment by Rapsey** [comment]
I was experiencing the same problem. Just tried installing from the maintenance branch and I can confirm this has solved the problem.

Probably not related to this issue but it might be worth pointing out that when doing this I get 3 TouchUI entries in the OcroPrint settings menu, of which only the third one works. I guess this might be because the maintenance branch isn't meant to be release-ready which is why I mention it here instead of creating an issue.

Thank you for fixing!

**Comment by Drzet** [comment]
Touch/mobile detection still doesn't work with the newest version. The mobile icon at the top doesn't work either

**Comment by BillyBlaze** [comment]
Thanks again all for reporting!

This has been released in 0.3.13

**Comment by Jan07576** [comment]
I just had similar issues with the latest version that I downloaded today.
