### ISSUE TITLE
TouchUI used in FRAMESET gets to login screen (and won't exit from there)

### ISSUE THREAD

**Issue by bolsoncerrado** [BillyBlaze/OctoPrint-TouchUI#372]
No matter what I do, whether I click LOGIN with empty fields or I correctly fill the login data fields, I can't go past the login screen on the LAN using a frameset call to the internal IPs of our touchui'zed printers :?

<img width="2460" alt="Captura de pantalla 2020-03-10 a las 11 33 31" src="https://user-images.githubusercontent.com/10992914/76304063-02013600-62c3-11ea-9bf0-c2a04283c8f2.png">

However calling each IP straight in a browser tab works fine :???

Happening on all mac browsers we have installed (Safari, Firefox and Chrome, latest versions each).

**Comment by BillyBlaze** [comment]
The login page is default OctoPrint functionality and TouchUI is not involved, any bugs involved in the login page should be reported on that end. I would start asking this question on the OctoPrint Community Forum; maybe it's a setting or maybe the login functionality doesn't allow OctoPrint to be loaded in framesets. This is all speculation since I don't know the login code-base.
