### ISSUE TITLE
Settings button works just once

### ISSUE THREAD

**Issue by pcfriend** [BillyBlaze/OctoPrint-TouchUI#40]
Hi Paul
TouchUI works great now. Its very useful to combine it with a touchscreen. Theres just one little problem: I crashed my raspberry last week, so I had to redo all the installation steps for Octoprint. This gave me the chance to update all my plugins. But now I have found a new bug in TouchUI. When I click the button "settings", you know the button with the three bars, and then exit the settings menu I wont be able to click the settings button again. This problem does only appear on the touch screen. On a PC it works just fine. I don't know really the reason for that issue, so I ask you for help. I also have installed the plugin System Command Editor. Maybe it has something to do with that?
Thank you for helping
Raphael

**Comment by BillyBlaze** [comment]
Thanks for reporting Raphael!

Just to be sure, you're running KWEB, OctoPrint 1.2.10 and TouchUI 0.3.3 now??

**Comment by pcfriend** [comment]
Thats correct.

On Sun, Apr 24, 2016 at 12:50 AM -0700, "Paul de Vries" notifications@github.com wrote:

Thanks for reporting Raphael!

Just to be sure, you're running KWEB, OctoPrint 1.2.10 and TouchUI 0.3.3 now??

---

**Comment by BillyBlaze** [comment]
Ok, I will investigate this problem a bit more, btw, if you're running Jessie, you might want to consider switching to the latest Chrome version. (it's in the Wiki)

**Comment by BillyBlaze** [comment]
Sorry, I forgot to test this in the latest KWEB browser and my fix (0.3.3) worked for 1.6.9 and lower (you have atleast 1.7.0). However since you're running higher then that means you have Jessie. Therefor with this bug I am dropping support for KWEB and add support for Chromium on Jessie.

So sorry for the troubles, but please upgrade your browser with these steps: https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(Chromium-&-Jessie)#upgrade-from-iceweasel--kweb

**Comment by pcfriend** [comment]
Hi PaulI run the latest Octopi image and as I know it's Raspbian Wheezy. Raphael

**Comment by BillyBlaze** [comment]
hmm so what version of kweb are you running then? 1.6.8? you might still have the installation directory in your home directory or to get the version run `sudo dpkg -l | grep kweb`

**Comment by BillyBlaze** [comment]
Read [#38](https://github.com/BillyBlaze/OctoPrint-TouchUI/issues/38#issuecomment-215197826) for more information

**Comment by pcfriend** [comment]
It says:
`ii  kweb                                  1.6.8-1                                 armhf        Minimal Kiosk Browser`
I think that's the right version, isn't it?

**Comment by BillyBlaze** [comment]
Yeah that looks right. I will investigate this a bit more. Maybe also do a fresh reinstall on my Wheezy card.

**Comment by pcfriend** [comment]
Hi PaulI just found the reason for this problem. But I haven't a solution. The settings button works fine when I don't use one of my custom system commands made with the plugin available in the plugin manager. When I use one of these commands the Button doesn't work anymore. However this problem does only appear on the touchscreen. On my iPhone  it works fine. So I guess the problem has something to do with kweb.  Maybe you know a solution but thats definitely not your job to fix kweb faults ;). Maybe I shoud change my OS to Jessie, so I can install chromium. Thank you for helping.  Raphael

**Comment by BillyBlaze** [comment]
Hi Raphael,

Thanks, that saves alot of figuring out. I do got to say as frontend developer it's required I get websites to work for a specific browser :smiley: 

But yeah, I bet this problem is more an issue in the custom system commands, and I doubt that the author will support kweb. However if you take the effort of installing Jessie and Chromium, then I bet it would be easily resolved. (+ better performance)

Your welcome and lemme know if there is any issues!
~Paul
