### ISSUE TITLE
Icons Broken in OctoPrint 1.5.0 - Probably FontAwesome Conflict

### ISSUE THREAD

**Issue by jneilliii** [BillyBlaze/OctoPrint-TouchUI#449]
OctoPrint 1.5.0 is being shipped with FontAwesome 5.15.1 and I believe the way that you are referencing the content is no longer viable or mismatched.  This is what they look like.

![image](https://user-images.githubusercontent.com/5249455/99867635-15221080-2b89-11eb-96fe-67265aa1db1d.png)

**Comment by cp2004** [comment]
Done some brief digging on this - seems that the font files are being reference with `FontAwesome`, which has now changed to `FontAwesome 5 Free` (or brands). Not sure of an easy way to adjust this that is not backwards-compatible. 
Touch UI also breaks icons it doesn't touch, for example the ones that are in the footer - since it applies its custom font family across them as well, which turns them to little boxes.

**Comment by cp2004** [comment]
I suppose TouchUI could bundle FA5 webfonts, for installs on OctoPrint <1.5.0. That might create strange issues, but then you would be able to change all the references like this to `Font Awesome 5 Free` (and obviously reference the font family file at the top of the file), without interfering when TouchUI is not loaded.

**Comment by BillyBlaze** [comment]
Thanks for reporting; this is fixed on the maintenance branch.

(commit message has the wrong version, it's 'Support for OctoPrint 1.5.0rc')

**Comment by cp2004** [comment]
Looks great, just tried it. Was about to report #450 as well, but you've beaten me to it... 🙂

**Comment by devildant** [comment]
hello, il try maintenance branch and last release same problem :(
