### ISSUE TITLE
Potential webcam issues

### ISSUE THREAD

**Issue by amoose136** [BillyBlaze/OctoPrint-TouchUI#75]
TouchUI used to work with my webcam (the standard octoprint interface still does) but after some update the camera tab now is blank even though a timelapse is being made in the background. Has anyone else had this problem or am I the only one? My version of octopi (1.2.18) is running on an RPi 3 with TouchUI (0.3.4) and I typically access it via Chrome or Chromium.

**Comment by BillyBlaze** [comment]
Hello, thanks for asking, sadly I am afraid you're the only one. I have upgraded everything to the latest versions and can still see the webcam feed.

**Comment by amoose136** [comment]
I disabled a bunch of plugins and the webcam came back in touchui after restarting so it appears there is some incompatibility with my plugins. I'll try and isolate it.

**Comment by amoose136** [comment]
So it appears that if the [Slicer plugin](http://plugins.octoprint.org/plugins/slicer/) is enabled, the webcam breaks only in ToughUI.

**Comment by BillyBlaze** [comment]
Thanks for finding this out.

There are some known issues with Slicer and TouchUI running locally on a linux machine. Basicly Slicer does no feature detection and executes javascript which does not work. I expect eventually that this javascript API will work. But that is dependent on Chromium.

The quickfix would be to add feature detection, but that is not the task for TouchUI.

**Comment by Salandora** [comment]
@BillyBlaze 
I have this Problem too hehe, but I tried to get a workaround/fix inside of TouchUI so I digged a bit around and found that this could really be a bug of touchui:

https://github.com/BillyBlaze/OctoPrint-TouchUI/blob/master/octoprint_touchui/static/js/touchui.bundled.js#L1867

cloneTo: '.tab-content'
I think this should be changed, because .tab-content could be used of many plugins and therefore is to common to be reliable. 

I changed it to this localy:
cloneTo: '#tabs + .tab-content'
this makes sure that the wanted .tab-content element has a previous id='#tabs' sibling.

for me this solved the webcam not shown problem.

**Comment by BillyBlaze** [comment]
Thanks for

**Comment by BillyBlaze** [comment]
@Salandora, thanks for finding this out 👍 

I will fix this in the upcoming release!

**Comment by amoose136** [comment]
Could be related but currently the webcam won't load on the pi if I use the touchui autostart script but will work if I launch a full x session and load it in Chrome from there. @Salandora's fix doesn't change this and the slicer plugin is disabled. This doesn't matter much though because if I can see the Pi, I can see the printer.

**Comment by BillyBlaze** [comment]
This has been fixed in the latest 0.3.7 release.
